version: "3.7"

services: 
    vue-app:
        container_name: vue-app
        build: 
            context: .
            dockerfile: dev.dockerfile
        ports: 
            - 80:8080
        volumes: 
            - ${PWD}:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true